version: '3.8'

services:
  coindesk-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CoinDeskApiDb;User Id=sa;Password=YourPassword123!;TrustServerCertificate=true
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    depends_on:
      - sqlserver
    networks:
      - coindesk-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU20-ubuntu-22.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - coindesk-network

volumes:
  sqlserver_data:

networks:
  coindesk-network:
    driver: bridge
